FROM jetbrains/qodana-php:2023.2 as qodana-php

FROM debian:11-slim

ENV JAVA_HOME=/opt/idea/jbr \
    DEVICEID= \
    QODANA_DOCKER=true \
    QODANA_CONF=/root/.config/idea \
    PATH=/opt/idea/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    HOME=/root \
    LC_ALL=en_US.UTF-8 \
    QODANA_DIST=/opt/idea \
    QODANA_DATA=/data

COPY --from=qodana-php /opt/idea /opt/idea

RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    curl https://packages.sury.org/php/README.txt | bash && \
    apt-get install -y nodejs php8.0-cli php8.0-mysql php8.0-curl php8.0-gd php8.0-xml php8.0-zip php8.0-opcache php8.0-mbstring php8.0-intl php8.0-imap php8.0-pgsql php8.0-soap php8.0-bcmath php8.0-redis && \
    rm -rf /var/cache/apt /var/lib/apt/ /tmp/* && \
    update-alternatives --install /usr/bin/java java $JAVA_HOME/bin/java 0 && \
    update-alternatives --install /usr/bin/javac javac $JAVA_HOME/bin/javac 0 && \
    update-alternatives --set java $JAVA_HOME/bin/java && \
    update-alternatives --set javac $JAVA_HOME/bin/javac && \
    mkdir -p /root/.config/idea && \
    mkdir -p /data/project && \
    chmod 777 -R /root && \
    chmod 777 -R /data && \
    chmod 666 /etc/passwd

COPY rootfs/ /
COPY --from=composer/composer:2-bin /composer /usr/bin/composer

WORKDIR /data/project

ENTRYPOINT ["/entrypoint.sh"]
